name: GitHub Actions Demo
run-name: ${{ github.actor }} abc
on:
  pull_request:
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Install Dependencies
        run: composer install --prefer-dist

      - name: Fix Style
        run: ./vendor/bin/pint -v