name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  pull_request:
env:
  GITHUB_OUTPUT: Monday
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Install Dependencies
        run: composer install --prefer-dist

      - name: Fix Style
        run: ./vendor/bin/pint -v

      - name: pwsh
        id: check_file_changed
        shell: pwsh
        run: |
          $diff = (git diff).Length -gt 0
          Write-Host "docs_changed::$diff" >> $GITHUB_OUTPUT

      - name: Set color
        id: random-color-generator
        run: echo "SELECTED_COLOR=green" >> $GITHUB_OUTPUT

      - name: Get color
        run: echo "The selected color is ${{ steps.random-color-generator.outputs.SELECTED_COLOR }}"

      - name: Commit report
        if: steps.check_file_changed.outputs.docs_changed == 'True'
        run: |
          git config --global user.name 'Your Name'
          git config --global user.email 'your-username@users.noreply.github.com'
          git commit -am "Commit report"
          git push
