name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  pull_request:
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Install Dependencies
        run: composer install --prefer-dist

      - name: Fix Style
        run: ./vendor/bin/pint -v

      - name: pwsh
        id: check_file_changed
        shell: pwsh
        run: |
          $diff = git diff
          Write-Host "::set-output name=docs_changed::$diff"

      - name: abc
        if: steps.check_file_changed.outputs.docs_changed == 'True'
        run: |
          echo "steps.check_file_changed.outputs.docs_changed"
          echo steps.check_file_changed.outputs.docs_changed

      - name: Commit report
        if: ${{ env.GITHUB_OUTPUT == 'True' }}
        run: |
          git config --global user.name 'Your Name'
          git config --global user.email 'your-username@users.noreply.github.com'
          git commit -am "Commit report"
          git push
